/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerEventTypesRouteImport } from './routes/owner.event-types'
import { Route as OwnerBookingsRouteImport } from './routes/owner.bookings'
import { Route as EventTypesEventTypeIdRouteImport } from './routes/event-types.$eventTypeId'
import { Route as OwnerEventTypesIndexRouteImport } from './routes/owner.event-types.index'
import { Route as OwnerEventTypesEventTypeIdEditRouteImport } from './routes/owner.event-types.$eventTypeId.edit'

const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerEventTypesRoute = OwnerEventTypesRouteImport.update({
  id: '/event-types',
  path: '/event-types',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerBookingsRoute = OwnerBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => OwnerRoute,
} as any)
const EventTypesEventTypeIdRoute = EventTypesEventTypeIdRouteImport.update({
  id: '/event-types/$eventTypeId',
  path: '/event-types/$eventTypeId',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerEventTypesIndexRoute = OwnerEventTypesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerEventTypesRoute,
} as any)
const OwnerEventTypesEventTypeIdEditRoute =
  OwnerEventTypesEventTypeIdEditRouteImport.update({
    id: '/$eventTypeId/edit',
    path: '/$eventTypeId/edit',
    getParentRoute: () => OwnerEventTypesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/owner': typeof OwnerRouteWithChildren
  '/event-types/$eventTypeId': typeof EventTypesEventTypeIdRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/event-types': typeof OwnerEventTypesRouteWithChildren
  '/owner/event-types/': typeof OwnerEventTypesIndexRoute
  '/owner/event-types/$eventTypeId/edit': typeof OwnerEventTypesEventTypeIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/owner': typeof OwnerRouteWithChildren
  '/event-types/$eventTypeId': typeof EventTypesEventTypeIdRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/event-types': typeof OwnerEventTypesIndexRoute
  '/owner/event-types/$eventTypeId/edit': typeof OwnerEventTypesEventTypeIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/owner': typeof OwnerRouteWithChildren
  '/event-types/$eventTypeId': typeof EventTypesEventTypeIdRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/event-types': typeof OwnerEventTypesRouteWithChildren
  '/owner/event-types/': typeof OwnerEventTypesIndexRoute
  '/owner/event-types/$eventTypeId/edit': typeof OwnerEventTypesEventTypeIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/owner'
    | '/event-types/$eventTypeId'
    | '/owner/bookings'
    | '/owner/event-types'
    | '/owner/event-types/'
    | '/owner/event-types/$eventTypeId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/owner'
    | '/event-types/$eventTypeId'
    | '/owner/bookings'
    | '/owner/event-types'
    | '/owner/event-types/$eventTypeId/edit'
  id:
    | '__root__'
    | '/'
    | '/owner'
    | '/event-types/$eventTypeId'
    | '/owner/bookings'
    | '/owner/event-types'
    | '/owner/event-types/'
    | '/owner/event-types/$eventTypeId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  EventTypesEventTypeIdRoute: typeof EventTypesEventTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/event-types': {
      id: '/owner/event-types'
      path: '/event-types'
      fullPath: '/owner/event-types'
      preLoaderRoute: typeof OwnerEventTypesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/bookings': {
      id: '/owner/bookings'
      path: '/bookings'
      fullPath: '/owner/bookings'
      preLoaderRoute: typeof OwnerBookingsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/event-types/$eventTypeId': {
      id: '/event-types/$eventTypeId'
      path: '/event-types/$eventTypeId'
      fullPath: '/event-types/$eventTypeId'
      preLoaderRoute: typeof EventTypesEventTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/event-types/': {
      id: '/owner/event-types/'
      path: '/'
      fullPath: '/owner/event-types/'
      preLoaderRoute: typeof OwnerEventTypesIndexRouteImport
      parentRoute: typeof OwnerEventTypesRoute
    }
    '/owner/event-types/$eventTypeId/edit': {
      id: '/owner/event-types/$eventTypeId/edit'
      path: '/$eventTypeId/edit'
      fullPath: '/owner/event-types/$eventTypeId/edit'
      preLoaderRoute: typeof OwnerEventTypesEventTypeIdEditRouteImport
      parentRoute: typeof OwnerEventTypesRoute
    }
  }
}

interface OwnerEventTypesRouteChildren {
  OwnerEventTypesIndexRoute: typeof OwnerEventTypesIndexRoute
  OwnerEventTypesEventTypeIdEditRoute: typeof OwnerEventTypesEventTypeIdEditRoute
}

const OwnerEventTypesRouteChildren: OwnerEventTypesRouteChildren = {
  OwnerEventTypesIndexRoute: OwnerEventTypesIndexRoute,
  OwnerEventTypesEventTypeIdEditRoute: OwnerEventTypesEventTypeIdEditRoute,
}

const OwnerEventTypesRouteWithChildren = OwnerEventTypesRoute._addFileChildren(
  OwnerEventTypesRouteChildren,
)

interface OwnerRouteChildren {
  OwnerBookingsRoute: typeof OwnerBookingsRoute
  OwnerEventTypesRoute: typeof OwnerEventTypesRouteWithChildren
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerBookingsRoute: OwnerBookingsRoute,
  OwnerEventTypesRoute: OwnerEventTypesRouteWithChildren,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OwnerRoute: OwnerRouteWithChildren,
  EventTypesEventTypeIdRoute: EventTypesEventTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
